config/routes.rb
Rails.application.routes.draw do
  resources :documentations
  resources :documentations
  resources :soft_skills
  resources :technical_skills
  resources :resources
  resources :communication_channels
  resources :communication_chanels
  resources :softwares
  resources :users
  resources :users

end

app/models/documentation.rb
class Documentation < ActiveRecord::Base
	belongs_to :software
end

app/controllers/documentations_controller.rb
class DocumentationsController < ApplicationController
  before_action :set_documentation, only: [:show, :edit, :update, :destroy]

  # GET /documentations
  # GET /documentations.json
  def index
    @documentations = Documentation.all
  end

  # GET /documentations/1
  # GET /documentations/1.json
  def show
  end

  # GET /documentations/new
  def new
    @documentation = Documentation.new
  end

  # GET /documentations/1/edit
  def edit
  end

  # POST /documentations
  # POST /documentations.json
  def create
    @documentation = Documentation.new(documentation_params)

    respond_to do |format|
      if @documentation.save
        format.html { redirect_to @documentation, notice: 'Documentation was successfully created.' }
        format.json { render :show, status: :created, location: @documentation }
      else
        format.html { render :new }
        format.json { render json: @documentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documentations/1
  # PATCH/PUT /documentations/1.json
  def update
    respond_to do |format|
      if @documentation.update(documentation_params)
        format.html { redirect_to @documentation, notice: 'Documentation was successfully updated.' }
        format.json { render :show, status: :ok, location: @documentation }
      else
        format.html { render :edit }
        format.json { render json: @documentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documentations/1
  # DELETE /documentations/1.json
  def destroy
    @documentation.destroy
    respond_to do |format|
      format.html { redirect_to documentations_url, notice: 'Documentation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_documentation
      @documentation = Documentation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def documentation_params
      params.require(:documentation).permit(:name, :description, :file)
    end
end

app/helpers/documentations_helper.rb
module DocumentationsHelper
end

app/views/documentations/_form.html.erb
<%= form_for(@documentation) do |f| %>
  <% if @documentation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@documentation.errors.count, "error") %> prohibited this documentation from being saved:</h2>

      <ul>
      <% @documentation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class=>"form-control wysihtml5", :rows=>8 %>
  </div>
  <div class="field">
    <%= f.label :file %><br>
    <%= f.text_area :file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documentations/edit.html.erb
<h1>Editing Documentation</h1>

<%= render 'form' %>

<%= link_to 'Show', @documentation %> |
<%= link_to 'Back', documentations_path %>

app/views/documentations/index.html.erb
<%- model_class = Documentation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:file) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @documentations.each do |documentation| %>
      <tr>
        <td><%= link_to documentation.id, documentation_path(documentation) %></td>
        <td><%= documentation.name %></td>
        <td><%= documentation.description %></td>
        <td><%= documentation.file %></td>
        <td><%=l documentation.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_documentation_path(documentation), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      documentation_path(documentation),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_documentation_path,
            :class => 'btn btn-primary' %>

app/views/documentations/new.html.erb
<h1>New Documentation</h1>

<%= render 'form' %>

<%= link_to 'Back', documentations_path %>

app/views/documentations/show.html.erb
<%- model_class = Documentation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @documentation.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @documentation.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:file) %>:</strong></dt>
  <dd><%= @documentation.file %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              documentation_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_documentation_path(@documentation), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              documentation_path(@documentation),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>