config/routes.rb
Rails.application.routes.draw do
  resources :documentations
  resources :documentations
  resources :soft_skills
  resources :technical_skills
  resources :resources
  resources :communication_channels
  resources :communication_chanels
  resources :softwares
  resources :users
  resources :users

end

app/models/technical_skill.rb
class TechnicalSkill < ActiveRecord::Base
	belongs_to :software

	def to_s
	  name
	end
end

app/controllers/technical_skills_controller.rb
class TechnicalSkillsController < ApplicationController
  before_action :set_technical_skill, only: [:show, :edit, :update, :destroy]

  # GET /technical_skills
  # GET /technical_skills.json
  def index
    @technical_skills = TechnicalSkill.all
  end

  # GET /technical_skills/1
  # GET /technical_skills/1.json
  def show
  end

  # GET /technical_skills/new
  def new
    @technical_skill = TechnicalSkill.new
  end

  # GET /technical_skills/1/edit
  def edit
  end

  # POST /technical_skills
  # POST /technical_skills.json
  def create
    @technical_skill = TechnicalSkill.new(technical_skill_params)

    respond_to do |format|
      if @technical_skill.save
        format.html { redirect_to @technical_skill, notice: 'Technical skill was successfully created.' }
        format.json { render :show, status: :created, location: @technical_skill }
      else
        format.html { render :new }
        format.json { render json: @technical_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /technical_skills/1
  # PATCH/PUT /technical_skills/1.json
  def update
    respond_to do |format|
      if @technical_skill.update(technical_skill_params)
        format.html { redirect_to @technical_skill, notice: 'Technical skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @technical_skill }
      else
        format.html { render :edit }
        format.json { render json: @technical_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /technical_skills/1
  # DELETE /technical_skills/1.json
  def destroy
    @technical_skill.destroy
    respond_to do |format|
      format.html { redirect_to technical_skills_url, notice: 'Technical skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technical_skill
      @technical_skill = TechnicalSkill.find(params[:id])
      puts "="*80, @technical_skill, "="*80
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technical_skill_params
      params.require(:technical_skill).permit(:name, :description)
    end
end

app/helpers/technical_skills_helper.rb
module TechnicalSkillsHelper
end

app/views/technical_skills/_form.html.erb
<%= form_for @technical_skill, :html => { :class => "form-horizontal resource" } do |f| %>

  <% if @technical_skill.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@resource.errors.count, "error") %> prohibited this technical skill from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @technical_skill.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :description, :class=>"form-control wysihtml5", :rows=>8 %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                resources_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/technical_skills/edit.html.erb
<h1>Editing Technical Skill</h1>

<%= render 'form' %>

<%= link_to 'Show', @technical_skill %> |
<%= link_to 'Back', technical_skills_path %>

app/views/technical_skills/index.html.erb
<%- model_class = TechnicalSkill -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @technical_skills.each do |technical_skill| %>
      <tr>
        <td><%= link_to technical_skill.id, technical_skill_path(technical_skill) %></td>
        <td><%= technical_skill.name %></td>
        <td><%= technical_skill.description %></td>
        <td><%=l technical_skill.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_technical_skill_path(technical_skill), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      technical_skill_path(technical_skill),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_technical_skill_path,
            :class => 'btn btn-primary' %>

app/views/technical_skills/new.html.erb
<h1>New Technical Skill</h1>

<%= render 'form' %>

<%= link_to 'Back', technical_skills_path %>

app/views/technical_skills/show.html.erb
<%- model_class = TechnicalSkill -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @technical_skill.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @technical_skill.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              technical_skill_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_technical_skill_path(@technical_skill), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              technical_skill_path(@technical_skill),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>