config/routes.rb
Rails.application.routes.draw do
  resources :documentations
  resources :documentations
  resources :soft_skills
  resources :technical_skills
  resources :resources
  resources :communication_channels
  resources :communication_chanels
  resources :softwares
  resources :users
  resources :users

end

app/models/software.rb
class Software < ActiveRecord::Base
	has_many :communication_channels
	has_many :documentation
	has_many :resource
	has_many :soft_skill
	has_many :technical_skill
end

app/controllers/softwares_controller.rb
class SoftwaresController < ApplicationController
  before_action :set_software, only: [:show, :edit, :update, :destroy]

  # GET /softwares
  # GET /softwares.json
  def index
    @softwares = Software.all
    @technical_skills = TechnicalSkill.all
    @soft_skills = SoftSkill.all
    @resources = Resource.all
    @communication_channels = CommunicationChannel.all
  end
 
  


  # GET /softwares/1
  # GET /softwares/1.json
  def show
    @technical_skills = TechnicalSkill.all
    @soft_skills = SoftSkill.all
    @resources = Resource.all
    @communication_channels = CommunicationChannel.all
  end

  # GET /softwares/new
  def new
    @software = Software.new
  end

  # GET /softwares/1/edit
  def edit
  end

  # POST /softwares
  # POST /softwares.json
  def create
    @software = Software.new(software_params)

    respond_to do |format|
      if @software.save
        format.html { redirect_to @software, notice: 'Software was successfully created.' }
        format.json { render :show, status: :created, location: @software }
      else
        format.html { render :new }
        format.json { render json: @software.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /softwares/1
  # PATCH/PUT /softwares/1.json
  def update
    respond_to do |format|
      if @software.update(software_params)
        format.html { redirect_to @software, notice: 'Software was successfully updated.' }
        format.json { render :show, status: :ok, location: @software }
      else
        format.html { render :edit }
        format.json { render json: @software.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /softwares/1
  # DELETE /softwares/1.json
  def destroy
    @software.destroy
    respond_to do |format|
      format.html { redirect_to softwares_url, notice: 'Software was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_software
      @software = Software.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def software_params
      params.require(:software).permit(:name, :description, :page, :contribution_model, :coding_standard, :contribution_standard, :setup_workspace, :issue_tracker, :repository, :communication_channels)
    end
end

app/helpers/softwares_helper.rb
module SoftwaresHelper
end

app/views/softwares/_form.html.erb
<%= form_for(@software) do |f| %>
  <% if @software.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@software.errors.count, "error") %> prohibited this software from being saved:</h2>

      <ul>
      <% @software.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

 <div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, :class=>"form-control wysihtml5", :rows=>8 %>
  </div>

  <div class="field">
    <%= f.label :page %><br>
    <%= f.url_field :page %>
  </div>
  <div class="field">
    <%= f.label :contribution_model %><br>
    <%= f.text_area :contribution_model, :class=>"form-control wysihtml5", :rows=>8 %>
  </div>
  <div class="field">
    <%= f.label :coding_standard %><br>
    <%= f.text_area :coding_standard, :class=>"form-control wysihtml5", :rows=>8 %>
  </div>
  <div class="field">
    <%= f.label :contribution_standard %><br>
    <%= f.text_area :contribution_standard, :class=>"form-control wysihtml5", :rows=>8 %>
  </div>
  <div class="field">
    <%= f.label :setup_workspace %><br>
    <%= f.text_area :setup_workspace, :class=>"form-control wysihtml5", :rows=>8 %>
  </div>
  <div class="field">
    <%= f.label :issue_tracker %><br>
    <%= f.url_field :issue_tracker %>
  </div>
  <div class="field">
    <%= f.label :repository %><br>
    <%= f.url_field :repository %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
    <%= f.label :communication_channels %><br>
    <%= f.collection_check_boxes(:communication_channels, CommunicationChannel.all, :id, :to_s, checked: @software.communication_channels.map(&:id)) %>
  </div>
    <%= link_to 'New Communication Channel', new_communication_channel_path %><br><br>
  <div class="field">


<div class="field">
    <%= f.label :resources %><br>
    <%= f.collection_check_boxes(:resource_ids, Resource.all, :id, :to_s) %>
  </div>
    <%= link_to 'New resources', new_resource_path %><br><br>
  <div class="field">

   <div class="field">
    <%= f.label :technical_skills %><br>
    <%= f.collection_check_boxes(:technical_skill_ids, TechnicalSkill.all, :id, :to_s) %>
  </div>
  <%= link_to 'New technical skills', new_technical_skill_path %><br><br>
  <div class="field">

   <div class="field">
    <%= f.label :soft_skills %><br>
    <%= f.collection_check_boxes(:soft_skill_ids, SoftSkill.all, :id, :to_s) %>
  </div>
  <%= link_to 'New Soft skills', new_soft_skill_path %><br><br>
  <div class="field">
    
    <%= f.label :documentation %><br>
  <%= link_to 'New documentation', new_documentation_path %><br><br>
<% end %>

app/views/softwares/edit.html.erb
<h1>Editing Software</h1>

<%= render 'form' %>

<%= link_to 'Show', @software %> |
<%= link_to 'Back', softwares_path %>

app/views/softwares/index.html.erb
<%- model_class = Software -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:page) %></th>
      <th><%= model_class.human_attribute_name(:contribution_model) %></th>
      <th><%= model_class.human_attribute_name(:coding_standard) %></th>
      <th><%= model_class.human_attribute_name(:contribution_standard) %></th>
      <th><%= model_class.human_attribute_name(:setup_workspace) %></th>
      <th><%= model_class.human_attribute_name(:issue_tracker) %></th>
      <th><%= model_class.human_attribute_name(:repository) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @softwares.each do |software| %>
      <tr>
        <td><%= link_to software.id, software_path(software) %></td>
        <td><%= software.name %></td>
        <td><%= software.description %></td>
        <td><%= software.page %></td>
        <td><%= software.contribution_model %></td>
        <td><%= software.coding_standard %></td>
        <td><%= software.contribution_standard %></td>
        <td><%= software.setup_workspace %></td>
        <td><%= software.issue_tracker %></td>
        <td><%= software.repository %></td>
        <td><%=l software.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_software_path(software), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      software_path(software),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_communication_channel_path,
            :class => 'btn btn-primary' %>

app/views/softwares/new.html.erb
<h1>New Software</h1>

<%= render 'form' %>

<%= link_to 'Back', softwares_path %>

app/views/softwares/show.html.erb
<p id="notice"><%= notice %></p>

<strong>How can I help you?</strong>

<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="#">Software</a></li>
  <li role="presentation"><a href="#how-to-start">How to Start</a></li>
  <li role="presentation"><a href="#talk">Talk to the Community</a></li>
  <li role="presentation"><a href="#setup">Setup your workspace</a></li>
  <li role="presentation"><a href="#code">Deal with code</a></li>
  <li role="presentation"><a href="#submit">Submit your changes</a></li>  
</ul>

<div class="jumbotron">
  <h1><%= @software.name %></h1>
  <div class="container">


<div class="panel panel-danger">
  <div class="panel-heading">About the project</div>
  <div class="panel-body">
  <%= @software.description %>
  <br>
  <strong>Page:</strong>
  <%= @software.page %>
  <br>
  <strong>Issue tracker:</strong>
  <%= @software.issue_tracker %>  
  <br>
  <strong>Repository:</strong>
  <%= @software.repository %>
  </div>
</div>

<div class="panel panel-danger">
  <div class="panel-heading">Technical skills required</div>
  <div class="panel-body">
    <% @technical_skills.map do |technical_skill|%>
        <%= link_to technical_skill.id, technical_skill_path(technical_skill) %>
        <%= technical_skill.name %>
        <%= technical_skill.description %>
        <br>
      <% end %>
</div>
</div>

<div class="panel panel-danger">
  <div class="panel-heading">Soft skills required</div>
  <div class="panel-body">
    <% @soft_skills.map do |soft_skill|%>
    <%= link_to soft_skill.id, soft_skill_path(soft_skill) %>
    <%= soft_skill.name %>
    <%= soft_skill.description%>
    <br>
    <% end %>
</div>
</div>

<div class="panel panel-danger">
  <div class="panel-heading">Resource available</div>
  <div class="panel-body">
    <% @resources.map do |resource|%>
    <% link_to resource.id, resource_path(resource) %>
    <% resource.name %>
    <% resource.description %>
    <br>
    <% end %>
</div>
</div>

</div>
</div>

<div class="jumbotron" id="how-to-start">
  <h1><%= @software.name %> - How to Start</h1>
  <div class="container">

<div class="panel panel-danger">
  <div class="panel-heading">Contribution Flow</div>
  <div class="panel-body">

  <%= @software.contribution_model %>

</div>
</div>
</div>
</div>


<div class="jumbotron" id="talk">
  <h1><%= @software.name %>   - Talk to the community</h1>
  <div class="container">

<div class="panel panel-danger">
  <div class="panel-heading">Community Suport</div>
  <div class="panel-body">

    <% @software.communication_channels.each do |communication_channel|%>
        <%= link_to communication_channel.name, communication_channel %>
        <%= communication_channel.description %>
        <%= communication_channel.standard %>
        <br>
      <% end %>
</div>
</div>
</div>
</div>

<div class="jumbotron" id="setup">
  <h1><%= @software.name %> - Workspace Setup</h1>
  <div class="container">


<div class="panel panel-danger">
  <div class="panel-heading">Resources provided by the project</div>
  <div class="panel-body">
    <%= @software.setup_workspace %>
</div>
</div>
</div>
</div>


<div class="jumbotron" id="code">
  <h1><%= @software.name %> - Code</h1>
  <div class="container">


<div class="panel panel-danger">
  <div class="panel-heading">Code documentation</div>
  <div class="panel-body">
  <%= @software.coding_standard %>  
</div>
</div>
</div>
</div>

<div class="jumbotron" id="submit">
  <h1><%= @software.name %> - Submit your change</h1>
  <div class="container">


<div class="panel panel-danger">
  <div class="panel-heading">Submiting your contribution</div>
  <div class="panel-body">
  <%= @software.contribution_standard %> 
</div>
</div>
</div>
</div>

<%= link_to t('.back', :default => t("helpers.links.back")),
              softwares_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_software_path(@software), :class => 'btn btn-default' %>